stages:
  - build
  - test
  - jacoco
  - checkstyle
  - spotbugs

build:
  stage: build
  script:
    - cd Lab/LabDemo
    - mvn compile

test:
  stage: test
  script:
    - cd Lab/LabDemo
    - mvn test

jacoco:
  stage: jacoco
  script:
    - cd Lab/LabDemo
    - mvn verify

checkstyle:
  stage: checkstyle
  script:
    - cd Lab/LabDemo
    - mvn checkstyle:check

spotbugs:
  stage: spotbugs
  script:
    - cd Lab/LabDemo
    - mvn spotbugs:check

# CW1
cw1 build:
  stage: build
  script:
    - cd CW1/CourseWork1
    - mvn compile

cw1 test:
  stage: test
  script:
    - cd CW1/CourseWork1
    - mvn test

cw1 jacoco:
  stage: jacoco
  script:
    - cd CW1/CourseWork1
    - mvn verify

cw1 checkstyle:
  stage: checkstyle
  script:
    - cd CW1/CourseWork1
    - mvn checkstyle:check

cw1 spotbugs:
  stage: spotbugs
  script:
    - cd CW1/CourseWork1
    - mvn spotbugs:check
